services:
  - type: web
    name: test-drive-booking-backend
    env: node
    plan: free
    rootDir: be
    buildCommand: yarn install
    startCommand: yarn migrate && yarn start
    healthCheckPath: /api/users
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
