services:
  - type: web
    name: test-drive-booking-backend
    env: node
    plan: free
    buildCommand: cd be && yarn install
    startCommand: cd be && yarn migrate:force && yarn start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # Google OAuth Configuration - All from Dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://minhduydanang.com,https://www.minhduydanang.com,http://localhost:3000,http://localhost:9200"
