services:
  - type: web
    name: test-drive-booking-backend
    env: node
    plan: free
    buildCommand: cd be && yarn install
    startCommand: cd be && yarn migrate:force && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
