export const ROUTERS = {
 USER: {
  HOME: "/",
  LOGIN: "/dang-nhap",
  REGISTER: "/register",
  PROFILE: "/thong-tin-ca-nhan",
  PRODUCTS: "/san-pham",
  PRODUCTS_DETAIL: "/san-pham/:id",
  SERVICE: "/dich-vu",
  PRICE_LIST: "/bang-gia",
  FAVORITES: "/yeu-thich",
  NEWS: "/tin-tuc",
  NEWS_DETAIL: "/tin-tuc-su-kien/:id",
  BOOKING: "/dat-lich",
 },
 AUTH: {
  SUCCESS: "/dang-nhap/thanh-cong",
},
 ADMIN: {
  DASHBOARD: "/admin",
  PRODUCTS: "/admin/products",
  PRODUCTS_ADD: "/admin/products/add",
  PRODUCTS_EDIT: "/admin/products/edit/:id",
  BOOKINGS: "/admin/bookings",
  BOOKINGS_DETAIL: "/admin/bookings/:id",
  
  USERS: "/admin/users",
  CATEGORIES: "/admin/categories",
  SERVICES: "/admin/services",
  SERVICES_ADD: "/admin/services/add",
  SERVICES_EDIT: "/admin/services/edit/:id",
  NEWS: "/admin/news",
  NEWS_ADD: "/admin/news/add",
  NEWS_EDIT: "/admin/news/edit/:id",
  SETTINGS: "/admin/settings",
  PRICE_LIST: "/admin/price-list",
  PRICE_LIST_ADD: "/admin/price-list/add",
  PRICE_LIST_EDIT: "/admin/price-list/edit/:id",
  PERMISSIONS: "/admin/permissions",
 },
};

export const colorOptions = [
  { value: 'blue', label: 'Blue' },
  { value: 'green', label: 'Green' },
  { value: 'purple', label: 'Purple' },
  { value: 'orange', label: 'Orange' },
  { value: 'red', label: 'Red' },
  { value: 'teal', label: 'Teal' },
  { value: 'indigo', label: 'Indigo' },
  { value: 'pink', label: 'Pink' },
  { value: 'yellow', label: 'Yellow' },
  { value: 'cyan', label: 'Cyan' },
  { value: 'violet', label: 'Violet' },
  { value: 'gray', label: 'Gray' },
];