export const ROUTERS = {
 USER: {
  HOME: "/",
  LOGIN: "/dang-nhap",
  REGISTER: "/register",
  PROFILE: "/profile",
  PRODUCTS: "/san-pham",
  PRODUCTS_DETAIL: "/san-pham/:id",
  SERVICE: "/dich-vu",
  PRICE_LIST: "/bang-gia",
  FAVORITES: "/yeu-thich",
  NEWS: "/tin-tuc",
  NEWS_DETAIL: "/tin-tuc-su-kien/:id",
  BOOKING: "/dat-lich",
 },
 ADMIN: {
  DASHBOARD: "/admin",
  PRODUCTS: "/admin/products",
  PRODUCTS_ADD: "/admin/products/add",
  PRODUCTS_EDIT: "/admin/products/edit/:id",
  BOOKINGS: "/admin/bookings",
  BOOKINGS_DETAIL: "/admin/bookings/:id",
  
  USERS: "/admin/users",
  CATEGORIES: "/admin/categories",
  SERVICES: "/admin/services",
  NEWS: "/admin/news",
  NEWS_ADD: "/admin/news/add",
  NEWS_EDIT: "/admin/news/edit/:id",
  SETTINGS: "/admin/settings",
 },
};